import pandas as pd
import numpy as np

def generate_temporal_features(df):
    # gets date features from date col
    df = df.copy()
    
    # ensure datetime formatting
    if not pd.api.types.is_datetime64_any_dtype(df["date"]):
        df["date"] = pd.to_datetime(df["date"])
        
    df["week"] = df["date"].dt.isocalendar().week.astype(int)
    df["month"] = df["date"].dt.month
    df["quarter"] = df["date"].dt.quarter
    
    return df


def generate_lag_and_rolling_features(df, target_col="quantity_clean"):
    # sorts chronologically, groups by sku, and calculates
    # lag and rolling window features
    df = df.copy()
    
    # makes sure data is sorted for time series shifts
    df = df.sort_values(["item_name", "date"])
    
    g = df.groupby("item_name")[target_col]
    
    # lag features
    df["lag_1"] = g.shift(1)
    df["lag_2"] = g.shift(2)
    df["lag_4"] = g.shift(4)
    
    # rolling features over four week window
    df["rolling_mean_4"] = g.shift(1).rolling(4).mean()
    df["rolling_std_4"] = g.shift(1).rolling(4).std()
    
    return df


def build_all_features(df, target_col="quantity_clean"):
    # full feature engineering pipeline
    # expects a df with date, item_name, and target col
    print("Engineering temporal and lagged features...")
    df = generate_temporal_features(df)
    df = generate_lag_and_rolling_features(df, target_col=target_col)
    
    # drop nas generated by shifting and rolling windows
    df = df.dropna().reset_index(drop=True)
    print(f"Feature engineering complete. Dataset shape: {df.shape}")
    
    return df


if __name__ == "__main__":
    # if ran as a script, process the clean orders directly into featured_sales
    import os
    
    input_path = "../../data/processed/weekly_orders_clean.csv"
    output_path = "../../data/processed/featured_sales.csv"
    
    if os.path.exists(input_path):
        print(f"Loading {input_path}...")
        raw_df = pd.read_csv(input_path)
        
        featured_df = build_all_features(raw_df)
        featured_df.to_csv(output_path, index=False)
        print(f"Saved featured dataset to {output_path}")
    else:
        print(f"File not found: {input_path}")
